spring.datasource.url=jdbc:mysql://127.0.0.1:3306/crowdsourcedWebsite?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Ballu@ri4567
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Server port (optional)
server.port=8080

logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

